# Generated by Django 4.2.3 on 2024-01-18 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Add_Bag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Book_Title', models.CharField(max_length=20)),
                ('UserName', models.CharField(max_length=20)),
                ('AddDate', models.DateField()),
                ('Datereturn', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Book_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Book_Id', models.IntegerField(default=0)),
                ('Book_Title', models.CharField(max_length=20)),
                ('Author', models.CharField(max_length=10)),
                ('Image', models.ImageField(upload_to='')),
                ('Publication', models.CharField(max_length=10)),
                ('Edition', models.CharField(max_length=10)),
                ('Price', models.IntegerField()),
                ('Date', models.DateField()),
                ('Quantity', models.PositiveIntegerField(default=0)),
                ('Status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Res_fin_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=20)),
                ('Book_Title', models.CharField(max_length=20)),
                ('Date_issue', models.DateField()),
                ('Date_return', models.DateField()),
                ('fine', models.IntegerField()),
                ('status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='User_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_Id', models.IntegerField(default='null')),
                ('UserType', models.CharField(max_length=10)),
                ('UserName', models.CharField(max_length=10)),
                ('Gender', models.CharField(max_length=10)),
                ('DateofBirth', models.DateField()),
                ('Address', models.CharField(max_length=30)),
                ('PhoneNumber', models.IntegerField()),
                ('EmailId', models.EmailField(max_length=254)),
            ],
        ),
    ]
