# Generated by Django 4.2.3 on 2024-01-25 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMAapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_details',
            name='Image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
