# Generated by Django 4.2.3 on 2024-01-25 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMAapp', '0002_alter_book_details_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Book_Title', models.CharField(max_length=20)),
                ('UserName', models.CharField(max_length=20)),
                ('AddDate', models.DateField()),
                ('Datereturn', models.DateTimeField()),
                ('status', models.CharField(max_length=10)),
            ],
        ),
    ]
